### ISSUE TITLE
StringUtil constructor is visible?

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/instrumentation-java#30]
The constructor seems to be visible for being able to be thrown, but solely for the purpose of testing.  This should be private, and the test should be removed.

The only valid reason I can think of for doing something like this is for code coverage, which can usually be fixed by adding a special comment.

**Comment by dinooliva** [comment]
Unfortunately, our internal build/coverage tools don't provide a special comment to ignore this sort of code and it adds noise to the coverage calculation. Since the class and the constructor is package-private and the constructor will throw an exception if invoked, I don't think it will cause much problem.

If you have a better approach, I'm certainly open to it.
