### ISSUE TITLE
Consider providing a no-op CensusContextFactory

### ISSUE THREAD

**Issue by zhangkun83** [google/instrumentation-java#41]
There will be cases where a Census-instrumented product would want to disable Census, or need a place-holder when Census.getCenusContextFactory() returns null. Yes they could implement their own no-op CensusContextFactory, but since this may be a common use case, it makes sense that Census provides a no-op impl as part of the census-api artfiact.

**Comment by dinooliva** [comment]
I have considered providing a default no-op implementation and have two concerns about do so:

1. We have a set of unit tests that are associated with the APIs and encode the behavior that any implementation of the APIs should provide (e.g. record some stats, grab the data, verify that the correct data is returned). A no-op implementation will not be able to pass those tests (since it will do nothing), which I believe will be confusing (to say the least).

2. Having a no-op implementation means that a client will not notice when their application has been built w/no stats support. I agree that having the application raise an exception during initialization of the stats library is not ideal but it is a clear indication that the application was built/linked incorrectly.

Thoughts?

**Comment by zhangkun83** [comment]
> We have a set of unit tests that are associated with the APIs and encode the behavior that any implementation of the APIs should provide (e.g. record some stats, grab the data, verify that the correct data is returned).

IMHO, the CensusContext API is only a reporting API, it doesn't mandate how the reported data is going to be propagated or used. An no-op implementation doesn't seem to violate the API contract.

There may also be cases where customer wants to disable stats reporting in some cases. It would be nice that they could just switch to a no-op Census factory instead of having an if-branch on every call site to CensusContext.

> Having a no-op implementation means that a client will not notice when their application has been built w/no stats support. 

Not necessarily. Providing an no-op implementation doesn't mean it's used silently. The applications still have choices.  They would try loading a real implementation, and if that fails, have the option to break or fall back to a no-op implementation.

**Comment by zhangkun83** [comment]
We have made our code to skip reporting logic if getStatsContextFactory() returns null, so we don't need the no-op impl any more.

**Comment by adriancole** [comment]
I like return null vs noop as well. It is easier to reason with (in context
of a staticly bound default) and hopefully people dont rely on classloader
singletons routinely anyway.

**Comment by bogdandrutu** [comment]
The problem with returning null vs noop is that every user library like gRPC has to write 3 lines to interact with everything:

StatsContextFactory statsContextFactory = Stats.getStatsContextFactory();
if (statsContextFactory != null) {
  statsContextFactory.DoSomething();
}

All the libraries will not have an implementation linked so they will always have to check for null which in my opinion is ugly and error prone.

**Comment by zhangkun83** [comment]
The argument for returning null is to give the API user more information to make more sensible decisions, e.g., skipping certain code-path or use an alternative reporting mechanism.
The argument for returning noop is that API users who don't really care can skip the null-checks.

Although right now my need for noop has vanished, if other people ask for it, we could add a noop-able method, e.g., `getStatsContextFactoryOrNoop()` in addition to the nullable method.

**Comment by adriancole** [comment]
This line of thinking assumes static accessor is encouraged. If it is edge
case then the extra lines of code to check null are also edge case right?
